In [4]:
import pandas as pd
df= pd.read_csv("data/data.csv")

In [2]:
print(df.shape)
print(df.head())
print(df.columns)

(500, 14)
        ID               Category                      Channel  \
0  VID-001  Machine Learning (ML)                  3Blue1Brown
1  VID-002  Machine Learning (ML)                  3Blue1Brown
2  VID-003  Machine Learning (ML)  StatQuest with Josh Starmer
3  VID-004  Machine Learning (ML)  StatQuest with Josh Starmer
4  VID-005  Machine Learning (ML)  StatQuest with Josh Starmer

                                               Title  \
0  But what is a neural network? | Deep learning ...
1  Gradient descent, how neural networks learn | ...
2          A Gentle Introduction to Machine Learning
3   Machine Learning Fundamentals: Bias and Variance
4    Machine Learning Fundamentals: Cross Validation

                                          URL Duration   Views  \
0  http://www.youtube.com/watch?v=aircAruvnKk    18:40  24.2M+
1  http://www.youtube.com/watch?v=IHZwWFHWa-w    20:33   9.5M+
2  http://www.youtube.com/watch?v=Gv9_4yMHFhI    12:45   1.6M+
3  http://www.youtube.com/watch?v=EuBBz3bI-aA     6:36   1.7M+
4  http://www.youtube.com/watch?v=fSytzGwwBVw     6:05   1.5M+

                          Explanation_Type  \
0       Mathematical & Geometric Intuition
1     Mathematical Optimization & Geometry
2   Pedagogical First-Principles Breakdown
3               Visual Error Decomposition
4  Step-by-Step Methodological Walkthrough

                                             Visuals  \
0  Custom Manim animations; dynamic 28x28 pixel g...
1  3D loss landscape topography; rolling ball phy...
2  Clean 2D scatter plots; color-coded training v...
3  Side-by-side curve fitting comparison; animate...
4  Color-coded 10-fold data partition blocks; ani...

                                            Examples  \
0  MNIST handwritten digit recognition focusing o...
1  Minimizing cost over 13,000 weights and biases...
2  Predicting love for StatQuest via decision tre...
3  Mouse weight vs mouse size prediction; straigh...
4  Evaluating model fit across patient health met...

                                           Analogies  \
0  Biological neurons firing vs mathematical dial...
1  A hiker descending a mountainous terrain in de...
2  Contrasting a straight linear trendline with a...
3  Underfitting is stubbornness (high bias); Over...
4  Rotational jury duty: giving every data partit...

                                           Real_Life  \
0  Human visual cortex processing; speech recogni...
1  Autonomous vehicle path optimization, facial r...
2  Athletic performance testing, clinical drug tr...
3  Students memorizing past exam questions verbat...
4  Financial credit risk modeling across fluctuat...

                                             Quality  \
0  Pristine studio acoustics; calm, deliberate ca...
1  Contemplative, clear voiceover; studio sound i...
2  Warm, energetic delivery; trademark acoustic j...
3  High-contrast minimalist slides; crisp voiceov...
4  Engaging conversational pacing; clean visual c...

                                   Creator_Takeaways
0  Hook with an intuitive mystery; never introduc...
1  Ground high-dimensional multivariable calculus...
2  Use silly/approachable toy examples to elimina...
3  Keep foundational concept videos under 7 minut...
4  Show algorithmic progression sequentially rath...
Index(['ID', 'Category', 'Channel', 'Title', 'URL', 'Duration', 'Views',
       'Explanation_Type', 'Visuals', 'Examples', 'Analogies', 'Real_Life',
       'Quality', 'Creator_Takeaways'],
      dtype='object')

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 14 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   ID                 500 non-null    object
 1   Category           500 non-null    object
 2   Channel            500 non-null    object
 3   Title              500 non-null    object
 4   URL                500 non-null    object
 5   Duration           500 non-null    object
 6   Views              500 non-null    object
 7   Explanation_Type   500 non-null    object
 8   Visuals            500 non-null    object
 9   Examples           500 non-null    object
 10  Analogies          500 non-null    object
 11  Real_Life          500 non-null    object
 12  Quality            500 non-null    object
 13  Creator_Takeaways  500 non-null    object
dtypes: object(14)
memory usage: 54.8+ KB

In [6]:
df.isnull().sum()

ID                   0
Category             0
Channel              0
Title                0
URL                  0
Duration             0
Views                0
Explanation_Type     0
Visuals              0
Examples             0
Analogies            0
Real_Life            0
Quality              0
Creator_Takeaways    0
dtype: int64

In [7]:
df.describe(include="all")

,ID,Category,Channel,Title,URL,Duration,Views,Explanation_Type,Visuals,Examples,Analogies,Real_Life,Quality,Creator_Takeaways
count,500,500,500,500,500,500,500,500,500,500,500,500,500,500
unique,500,25,187,500,500,442,329,495,500,500,500,500,495,500
top,VID-500,Machine Learning (ML),StatQuest with Josh Starmer,"Jim Keller: Moore's Law, Microprocessors, and ...",http://www.youtube.com/watch?v=Nb2tebYAaOA,7:08,1.1M+,Ultra-Fast Concept Distillation,"Studio interview, discussion of transistor phy...","Designing Apple A4/A5 chips, AMD Zen architect...",Designing a microprocessor is like organizing ...,"AI hardware acceleration, semiconductor indust...","Studio 4K video, crisp lapel microphone, lumin...",The 'city with billions of people delivering m...
freq,1,67,44,1,1,4,8,2,1,1,1,1,2,1

In [8]:
for column in df.columns:
    print("\n", column)
    print(df[column].head(5))

 ID
0    VID-001
1    VID-002
2    VID-003
3    VID-004
4    VID-005
Name: ID, dtype: object

 Category
0    Machine Learning (ML)
1    Machine Learning (ML)
2    Machine Learning (ML)
3    Machine Learning (ML)
4    Machine Learning (ML)
Name: Category, dtype: object

 Channel
0                    3Blue1Brown
1                    3Blue1Brown
2    StatQuest with Josh Starmer
3    StatQuest with Josh Starmer
4    StatQuest with Josh Starmer
Name: Channel, dtype: object

 Title
0    But what is a neural network? | Deep learning ...
1    Gradient descent, how neural networks learn | ...
2            A Gentle Introduction to Machine Learning
3     Machine Learning Fundamentals: Bias and Variance
4      Machine Learning Fundamentals: Cross Validation
Name: Title, dtype: object

 URL
0    http://www.youtube.com/watch?v=aircAruvnKk
1    http://www.youtube.com/watch?v=IHZwWFHWa-w
2    http://www.youtube.com/watch?v=Gv9_4yMHFhI
3    http://www.youtube.com/watch?v=EuBBz3bI-aA
4    http://www.youtube.com/watch?v=fSytzGwwBVw
Name: URL, dtype: object

 Duration
0    18:40
1    20:33
2    12:45
3     6:36
4     6:05
Name: Duration, dtype: object

 Views
0    24.2M+
1     9.5M+
2     1.6M+
3     1.7M+
4     1.5M+
Name: Views, dtype: object

 Explanation_Type
0         Mathematical & Geometric Intuition
1       Mathematical Optimization & Geometry
2     Pedagogical First-Principles Breakdown
3                 Visual Error Decomposition
4    Step-by-Step Methodological Walkthrough
Name: Explanation_Type, dtype: object

 Visuals
0    Custom Manim animations; dynamic 28x28 pixel g...
1    3D loss landscape topography; rolling ball phy...
2    Clean 2D scatter plots; color-coded training v...
3    Side-by-side curve fitting comparison; animate...
4    Color-coded 10-fold data partition blocks; ani...
Name: Visuals, dtype: object

 Examples
0    MNIST handwritten digit recognition focusing o...
1    Minimizing cost over 13,000 weights and biases...
2    Predicting love for StatQuest via decision tre...
3    Mouse weight vs mouse size prediction; straigh...
4    Evaluating model fit across patient health met...
Name: Examples, dtype: object

 Analogies
0    Biological neurons firing vs mathematical dial...
1    A hiker descending a mountainous terrain in de...
2    Contrasting a straight linear trendline with a...
3    Underfitting is stubbornness (high bias); Over...
4    Rotational jury duty: giving every data partit...
Name: Analogies, dtype: object

 Real_Life
0    Human visual cortex processing; speech recogni...
1    Autonomous vehicle path optimization, facial r...
2    Athletic performance testing, clinical drug tr...
3    Students memorizing past exam questions verbat...
4    Financial credit risk modeling across fluctuat...
Name: Real_Life, dtype: object

 Quality
0    Pristine studio acoustics; calm, deliberate ca...
1    Contemplative, clear voiceover; studio sound i...
2    Warm, energetic delivery; trademark acoustic j...
3    High-contrast minimalist slides; crisp voiceov...
4    Engaging conversational pacing; clean visual c...
Name: Quality, dtype: object

 Creator_Takeaways
0    Hook with an intuitive mystery; never introduc...
1    Ground high-dimensional multivariable calculus...
2    Use silly/approachable toy examples to elimina...
3    Keep foundational concept videos under 7 minut...
4    Show algorithmic progression sequentially rath...
Name: Creator_Takeaways, dtype: object

In [9]:
g = df.isna().all()
g

ID                   False
Category             False
Channel              False
Title                False
URL                  False
Duration             False
Views                False
Explanation_Type     False
Visuals              False
Examples             False
Analogies            False
Real_Life            False
Quality              False
Creator_Takeaways    False
dtype: bool

In [10]:
empty_columns = df.columns[df.isna().all()].tolist()

print("Empty columns:")
print(empty_columns)


df = df.drop(columns=empty_columns)

print("\nNew shape:", df.shape)

Empty columns:
[]

New shape: (500, 14)

In [11]:
df

,ID,Category,Channel,Title,URL,Duration,Views,Explanation_Type,Visuals,Examples,Analogies,Real_Life,Quality,Creator_Takeaways
0,VID-001,Machine Learning (ML),3Blue1Brown,But what is a neural network? | Deep learning ...,http://www.youtube.com/watch?v=aircAruvnKk,18:40,24.2M+,Mathematical & Geometric Intuition,Custom Manim animations; dynamic 28x28 pixel g...,MNIST handwritten digit recognition focusing o...,Biological neurons firing vs mathematical dial...,Human visual cortex processing; speech recogni...,"Pristine studio acoustics; calm, deliberate ca...",Hook with an intuitive mystery; never introduc...
1,VID-002,Machine Learning (ML),3Blue1Brown,"Gradient descent, how neural networks learn | ...",http://www.youtube.com/watch?v=IHZwWFHWa-w,20:33,9.5M+,Mathematical Optimization & Geometry,3D loss landscape topography; rolling ball phy...,"Minimizing cost over 13,000 weights and biases...",A hiker descending a mountainous terrain in de...,"Autonomous vehicle path optimization, facial r...","Contemplative, clear voiceover; studio sound i...",Ground high-dimensional multivariable calculus...
2,VID-003,Machine Learning (ML),StatQuest with Josh Starmer,A Gentle Introduction to Machine Learning,http://www.youtube.com/watch?v=Gv9_4yMHFhI,12:45,1.6M+,Pedagogical First-Principles Breakdown,Clean 2D scatter plots; color-coded training v...,Predicting love for StatQuest via decision tre...,Contrasting a straight linear trendline with a...,"Athletic performance testing, clinical drug tr...","Warm, energetic delivery; trademark acoustic j...",Use silly/approachable toy examples to elimina...
3,VID-004,Machine Learning (ML),StatQuest with Josh Starmer,Machine Learning Fundamentals: Bias and Variance,http://www.youtube.com/watch?v=EuBBz3bI-aA,6:36,1.7M+,Visual Error Decomposition,Side-by-side curve fitting comparison; animate...,Mouse weight vs mouse size prediction; straigh...,Underfitting is stubbornness (high bias); Over...,Students memorizing past exam questions verbat...,High-contrast minimalist slides; crisp voiceov...,Keep foundational concept videos under 7 minut...
4,VID-005,Machine Learning (ML),StatQuest with Josh Starmer,Machine Learning Fundamentals: Cross Validation,http://www.youtube.com/watch?v=fSytzGwwBVw,6:05,1.5M+,Step-by-Step Methodological Walkthrough,Color-coded 10-fold data partition blocks; ani...,Evaluating model fit across patient health met...,Rotational jury duty: giving every data partit...,Financial credit risk modeling across fluctuat...,Engaging conversational pacing; clean visual c...,Show algorithmic progression sequentially rath...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,VID-496,Agentic AI & Multi-Agent Systems,Telusko,Getting Structured Output in JSON format,http://www.youtube.com/watch?v=CllLqPwCjD4,9:15,14K+,Hands-On Python Developer Tutorial,"Python script connecting to LLM API, defining ...",Converting user travel inquiries into clean JS...,A digital customs declaration form where every...,"Backend API pipelines, automating form submiss...","Friendly, energetic Indian English educator st...",Demonstrate the validation step: always catch ...
496,VID-497,Generative AI & Diffusion Models,IBM Technology,Predictive vs Generative AI: How They Work and...,http://www.youtube.com/watch?v=phOhGqpXss4,11:59,61K+,Architectural Taxonomy & Decision Framework,Lightboard comparison dividing machine learnin...,Contrasting credit default risk scoring (predi...,A meteorologist predicting tomorrow's weather ...,Enterprise generative AI strategy and risk gov...,"Pristine studio lightboard, clear neon markers...",Provide a clear decision matrix: use Predictiv...
497,VID-498,Academic Lectures & Foundational Courses,DeepLearningAI,Multitask Learning (C3W2L08),http://www.youtube.com/watch?v=UdXfsAr4Gjw,13:00,82K+,Shared Representation & Joint Loss Optimization,Neural network with shared trunk features spli...,"Autonomous driving: detecting pedestrians, sto...","A student studying for an decathlon: running, ...",Perception backbones in autonomous vehicles (T...,"Clear blackboard diagrams, patient explanation...",Explain when multi-task learning beats separat...
498,VID-499,Natural Language Processing (NLP),Yannic Kilcher,DeBERTa: Decoding-enhanced BERT with Disentang...,http://www.youtube.com/watch?v=_c6A33Fg5Ns,45:14:00,23K+,Disentangled Attention & Enhanced Mask Decoding,Disentangled attention matrices separating con...,Outperforming human baselines on SuperGLUE nat...,Describing an actor in a play by both who they...,High-accuracy sentence classification and lega...,"Deep academic paper analysis, clear blackboard...",Explain Disentangled Attention: attention betw...
499,VID-500,Hardware Acceleration & AI Silicon,Lex Fridman,"Jim Keller: Moore's Law, Microprocessors, and ...",http://www.youtube.com/watch?v=Nb2tebYAaOA,1:34:44,738K+,Microprocessor Architecture & First-Principles...,"Studio interview, discussion of transistor phy...","Designing Apple A4/A5 chips, AMD Zen architect...",Designing a microprocessor is like organizing ...,"AI hardware acceleration, semiconductor indust...",Legendary microprocessor architect Jim Keller ...,The 'city with billions of people delivering m...

In [12]:
missing = df.isnull().sum()

print(missing)

ID                   0
Category             0
Channel              0
Title                0
URL                  0
Duration             0
Views                0
Explanation_Type     0
Visuals              0
Examples             0
Analogies            0
Real_Life            0
Quality              0
Creator_Takeaways    0
dtype: int64

In [13]:
df.describe(include="all")

,ID,Category,Channel,Title,URL,Duration,Views,Explanation_Type,Visuals,Examples,Analogies,Real_Life,Quality,Creator_Takeaways
count,500,500,500,500,500,500,500,500,500,500,500,500,500,500
unique,500,25,187,500,500,442,329,495,500,500,500,500,495,500
top,VID-500,Machine Learning (ML),StatQuest with Josh Starmer,"Jim Keller: Moore's Law, Microprocessors, and ...",http://www.youtube.com/watch?v=Nb2tebYAaOA,7:08,1.1M+,Ultra-Fast Concept Distillation,"Studio interview, discussion of transistor phy...","Designing Apple A4/A5 chips, AMD Zen architect...",Designing a microprocessor is like organizing ...,"AI hardware acceleration, semiconductor indust...","Studio 4K video, crisp lapel microphone, lumin...",The 'city with billions of people delivering m...
freq,1,67,44,1,1,4,8,2,1,1,1,1,2,1

In [14]:
for column in df.columns:
    print("\n", column)
    print(df[column].head(5))

 ID
0    VID-001
1    VID-002
2    VID-003
3    VID-004
4    VID-005
Name: ID, dtype: object

 Category
0    Machine Learning (ML)
1    Machine Learning (ML)
2    Machine Learning (ML)
3    Machine Learning (ML)
4    Machine Learning (ML)
Name: Category, dtype: object

 Channel
0                    3Blue1Brown
1                    3Blue1Brown
2    StatQuest with Josh Starmer
3    StatQuest with Josh Starmer
4    StatQuest with Josh Starmer
Name: Channel, dtype: object

 Title
0    But what is a neural network? | Deep learning ...
1    Gradient descent, how neural networks learn | ...
2            A Gentle Introduction to Machine Learning
3     Machine Learning Fundamentals: Bias and Variance
4      Machine Learning Fundamentals: Cross Validation
Name: Title, dtype: object

 URL
0    http://www.youtube.com/watch?v=aircAruvnKk
1    http://www.youtube.com/watch?v=IHZwWFHWa-w
2    http://www.youtube.com/watch?v=Gv9_4yMHFhI
3    http://www.youtube.com/watch?v=EuBBz3bI-aA
4    http://www.youtube.com/watch?v=fSytzGwwBVw
Name: URL, dtype: object

 Duration
0    18:40
1    20:33
2    12:45
3     6:36
4     6:05
Name: Duration, dtype: object

 Views
0    24.2M+
1     9.5M+
2     1.6M+
3     1.7M+
4     1.5M+
Name: Views, dtype: object

 Explanation_Type
0         Mathematical & Geometric Intuition
1       Mathematical Optimization & Geometry
2     Pedagogical First-Principles Breakdown
3                 Visual Error Decomposition
4    Step-by-Step Methodological Walkthrough
Name: Explanation_Type, dtype: object

 Visuals
0    Custom Manim animations; dynamic 28x28 pixel g...
1    3D loss landscape topography; rolling ball phy...
2    Clean 2D scatter plots; color-coded training v...
3    Side-by-side curve fitting comparison; animate...
4    Color-coded 10-fold data partition blocks; ani...
Name: Visuals, dtype: object

 Examples
0    MNIST handwritten digit recognition focusing o...
1    Minimizing cost over 13,000 weights and biases...
2    Predicting love for StatQuest via decision tre...
3    Mouse weight vs mouse size prediction; straigh...
4    Evaluating model fit across patient health met...
Name: Examples, dtype: object

 Analogies
0    Biological neurons firing vs mathematical dial...
1    A hiker descending a mountainous terrain in de...
2    Contrasting a straight linear trendline with a...
3    Underfitting is stubbornness (high bias); Over...
4    Rotational jury duty: giving every data partit...
Name: Analogies, dtype: object

 Real_Life
0    Human visual cortex processing; speech recogni...
1    Autonomous vehicle path optimization, facial r...
2    Athletic performance testing, clinical drug tr...
3    Students memorizing past exam questions verbat...
4    Financial credit risk modeling across fluctuat...
Name: Real_Life, dtype: object

 Quality
0    Pristine studio acoustics; calm, deliberate ca...
1    Contemplative, clear voiceover; studio sound i...
2    Warm, energetic delivery; trademark acoustic j...
3    High-contrast minimalist slides; crisp voiceov...
4    Engaging conversational pacing; clean visual c...
Name: Quality, dtype: object

 Creator_Takeaways
0    Hook with an intuitive mystery; never introduc...
1    Ground high-dimensional multivariable calculus...
2    Use silly/approachable toy examples to elimina...
3    Keep foundational concept videos under 7 minut...
4    Show algorithmic progression sequentially rath...
Name: Creator_Takeaways, dtype: object

In [15]:
df = df.drop_duplicates()

df["Title"] = df["Title"].fillna("")
df["Channel"] = df["Channel"].fillna("")
df["Examples"] = df["Examples"].fillna("")
df["Analogies"] = df["Analogies"].fillna("")
df["Visuals"] = df["Visuals"].fillna("")

In [16]:
text_columns = [
    "Title",
    "Explanation_Type",
    "Visuals",
    "Examples",
    "Analogies",
    "Real_Life",
    "Quality",
    "Creator_Takeaways"
]

for col in text_columns:
    df[col] = df[col].fillna("").astype(str)

In [17]:
def duration_to_seconds(duration):

    parts = duration.split(":")

    if len(parts) == 2:
        minutes, seconds = map(int, parts)
        return minutes * 60 + seconds

    if len(parts) == 3:
        hours, minutes, seconds = map(int, parts)
        return hours * 3600 + minutes * 60 + seconds

    return None

In [18]:
df["duration_seconds"] = df["Duration"].apply(duration_to_seconds)

In [19]:
def convert_views(x):

    x = str(x).replace("+", "").strip()

    if x.endswith("M"):
        return float(x[:-1]) * 1_000_000

    if x.endswith("K"):
        return float(x[:-1]) * 1_000

    return float(x)

In [20]:
df["views_numeric"] = df["Views"].apply(convert_views)

In [21]:
df["combined_text"] = (
    "Title: " + df["Title"] +
    "\nExplanation: " + df["Explanation_Type"] +
    "\nVisuals: " + df["Visuals"] +
    "\nExamples: " + df["Examples"] +
    "\nAnalogies: " + df["Analogies"] +
    "\nApplications: " + df["Real_Life"] +
    "\nQuality: " + df["Quality"] +
    "\nTakeaway: " + df["Creator_Takeaways"]
)

In [22]:
print(df["combined_text"].iloc[0])

Title: But what is a neural network? | Deep learning chapter 1
Explanation: Mathematical & Geometric Intuition
Visuals: Custom Manim animations; dynamic 28x28 pixel grid activations; colored weight synapses (green/red); layered node transformations.
Examples: MNIST handwritten digit recognition focusing on handwritten '3's vs other digits.
Analogies: Biological neurons firing vs mathematical dials/weights (0 to 1); layered abstraction hierarchy (pixels -> edges -> loops -> digits).
Applications: Human visual cortex processing; speech recognition acoustic decomposition; YouTube recommendation algorithms.
Quality: Pristine studio acoustics; calm, deliberate cadence (~130 wpm); subtle musical scoring; 1080p razor-sharp vector graphics.
Takeaway: Hook with an intuitive mystery; never introduce formulas before visual intuition; break black boxes into modular components.

In [23]:
df["has_analogy"] = (
    df["Analogies"].str.len() > 10
).astype(int)

In [24]:
df["has_example"] = (
    df["Examples"].str.len() > 10
).astype(int)

In [25]:
df["has_visual"] = (
    df["Visuals"].str.len() > 10
).astype(int)

In [26]:
df["has_visual"] = (
    df["Visuals"].str.len() > 10
).astype(int)

In [27]:
df["has_math"] = df["combined_text"].str.contains(
    r"formula|equation|mathematical|calculus|derivation|geometry|gradient",
    case=False,
    regex=True
).astype(int)

In [28]:
df["has_code"] = df["combined_text"].str.contains(
    r"code|python|pytorch|tensorflow|programming|terminal|implementation",
    case=False,
    regex=True
).astype(int)

In [29]:
df["has_application"] = (
    df["Real_Life"].str.len() > 10
).astype(int)

In [30]:
print(df.shape)
print(df.columns.tolist())

(500, 23)
['ID', 'Category', 'Channel', 'Title', 'URL', 'Duration', 'Views', 'Explanation_Type', 'Visuals', 'Examples', 'Analogies', 'Real_Life', 'Quality', 'Creator_Takeaways', 'duration_seconds', 'views_numeric', 'combined_text', 'has_analogy', 'has_example', 'has_visual', 'has_math', 'has_code', 'has_application']

In [32]:
df.to_csv(
    "data/processed/videos_clean.csv",
    index=False
)

print("Cleaned dataset saved successfully.")

Cleaned dataset saved successfully.

In [33]:
import numpy as np

In [34]:
annotation_columns = [
    "Clarity",
    "Correctness",
    "Visual",
    "Examples",
    "Analogy",
    "Practical",
    "Structure"
]

annotation_df = df[["ID", "Title", "Category"]].copy()

for col in annotation_columns:
    annotation_df[col] = np.nan

annotation_df.head()

,ID,Title,Category,Clarity,Correctness,Visual,Examples,Analogy,Practical,Structure
0,VID-001,But what is a neural network? | Deep learning ...,Machine Learning (ML),NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,VID-002,"Gradient descent, how neural networks learn | ...",Machine Learning (ML),NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,VID-003,A Gentle Introduction to Machine Learning,Machine Learning (ML),NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,VID-004,Machine Learning Fundamentals: Bias and Variance,Machine Learning (ML),NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,VID-005,Machine Learning Fundamentals: Cross Validation,Machine Learning (ML),NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [35]:
annotation_df.to_csv(
    "data/processed/video_annotations.csv",
    index=False
)

print("Annotation template created!")

Annotation template created!

In [36]:
annotations = pd.read_csv(
    "data/processed/video_annotations.csv"
)

In [37]:
print(annotations[annotation_columns].isna().sum())

Clarity        500
Correctness    500
Visual         500
Examples       500
Analogy        500
Practical      500
Structure      500
dtype: int64

In [38]:
annotations["quality_score"] = (
    annotations[annotation_columns]
    .mean(axis=1) * 20
)